Bag of Words represents text by word counts, ignoring grammar and word order.

Example:
- S1: "fraud detected in transaction"
- S2: "transaction fraud fraud detected"

BoW treats both as almost the same, because:
- same words
- similar counts
- order doesn’t matter

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "fraud detected in transaction",
    "transaction fraud fraud detected"
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['detected' 'fraud' 'in' 'transaction']
[[1 1 1 1]
 [1 2 0 1]]


---

In [3]:
#Checking on an actual spam file

import pandas as pd

messages = pd.read_csv('/Users/mayankdixit/Documents/AI_Learning_Conda/NLP Machine Learning/spam.csv',encoding = 'latin-1')


In [4]:
messages

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [5]:
messages = messages[['v1', 'v2']]
messages.columns = ['label', 'message']

In [6]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [7]:
#Data Preprocessing

import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/mayankdixit/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [8]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
stop_words = set(stopwords.words('english'))


In [9]:
corpus = []

for message in messages['message']:

    # 1. Remove non-alphabetic characters
    text = re.sub('[^a-zA-Z]', ' ', message)

    # 2. Convert to lowercase
    text = text.lower()

    # 3. Split into words
    words = text.split()

    # 4. Remove stopwords
    filtered_words = []
    for word in words:
        if word not in stop_words:
            filtered_words.append(word)

    # 5. Apply stemming
    stemmed_words = []
    for word in filtered_words:
        stemmed_words.append(ps.stem(word))

    # 6. Rebuild sentence
    clean_text = ' '.join(stemmed_words)

    # 7. Add to corpus
    corpus.append(clean_text)


In [10]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [11]:
# Creating BoW Model

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=2500) # only top 2500 features will be taken. binary = True for binary BoW
X = cv.fit_transform(corpus).toarray()
y = messages['label']

print("BoW shape:", X.shape)
print("Example features:", cv.get_feature_names_out()[:20])

BoW shape: (5572, 2500)
Example features: ['aah' 'aathi' 'abi' 'abiola' 'abl' 'abt' 'abta' 'ac' 'acc' 'accept'
 'access' 'accid' 'accident' 'accordingli' 'account' 'ach' 'across' 'act'
 'action' 'activ']


In [12]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 2500))

In [13]:
y

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: label, Length: 5572, dtype: object

In [14]:
cv.vocabulary_

{'go': np.int64(870),
 'point': np.int64(1613),
 'crazi': np.int64(493),
 'avail': np.int64(140),
 'bugi': np.int64(272),
 'great': np.int64(894),
 'world': np.int64(2440),
 'la': np.int64(1131),
 'cine': np.int64(391),
 'got': np.int64(885),
 'wat': np.int64(2370),
 'ok': np.int64(1509),
 'lar': np.int64(1143),
 'joke': np.int64(1089),
 'wif': np.int64(2408),
 'oni': np.int64(1517),
 'free': np.int64(809),
 'entri': np.int64(679),
 'wkli': np.int64(2429),
 'comp': np.int64(431),
 'win': np.int64(2412),
 'fa': np.int64(722),
 'cup': np.int64(510),
 'final': np.int64(765),
 'tkt': np.int64(2170),
 'st': np.int64(2014),
 'may': np.int64(1315),
 'text': np.int64(2129),
 'receiv': np.int64(1722),
 'question': np.int64(1684),
 'std': np.int64(2025),
 'txt': np.int64(2233),
 'rate': np.int64(1703),
 'appli': np.int64(98),
 'dun': np.int64(641),
 'say': np.int64(1814),
 'earli': np.int64(645),
 'alreadi': np.int64(66),
 'nah': np.int64(1446),
 'think': np.int64(2144),
 'goe': np.int64(873),
 

In [20]:
print(type(cv.vocabulary_)) #This returns a dictionary with the word (n-gram) and its index.

print(len(cv.vocabulary_)) # we have just taken 2500 features



<class 'dict'>
2500


##### N Gram -  n-gram is a sequence of n consecutive tokens.
    - Unigram (1-gram) → single words
    - Bigram (2-gram) → two consecutive words
    - Trigram (3-gram) → three consecutive words

So why does N- gram exists?

The Bag of Words ignore the word order which creates dangerous cases like:
- fraudulent
- not fraudulent

Unigram treat these as almost identical, but Bigram fix this by capturing the local context
- "not fraudulent" becomes a disctinct feature
- "fraudulent" alone no longer dominates

So the purpose of "n-grams" is to capture the meaning theat comes from word combinations.


In [ ]:
#Let's see an example 

#Unigrams - these are deafult params inside CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(ngram_range=(1, 1))
X = cv.fit_transform(corpus)


In [30]:
cv.vocabulary_

{'go': 2148,
 'jurong': 2794,
 'point': 4046,
 'crazi': 1162,
 'avail': 377,
 'bugi': 732,
 'great': 2222,
 'world': 6060,
 'la': 2898,
 'buffet': 730,
 'cine': 957,
 'got': 2185,
 'amor': 188,
 'wat': 5886,
 'ok': 3718,
 'lar': 2926,
 'joke': 2761,
 'wif': 5982,
 'oni': 3743,
 'free': 1990,
 'entri': 1659,
 'wkli': 6026,
 'comp': 1051,
 'win': 5993,
 'fa': 1777,
 'cup': 1212,
 'final': 1875,
 'tkt': 5474,
 'st': 5044,
 'may': 3239,
 'text': 5361,
 'receiv': 4350,
 'question': 4268,
 'std': 5072,
 'txt': 5629,
 'rate': 4313,
 'appli': 260,
 'dun': 1538,
 'say': 4595,
 'earli': 1555,
 'hor': 2450,
 'alreadi': 162,
 'nah': 3493,
 'think': 5407,
 'goe': 2152,
 'usf': 5743,
 'live': 3035,
 'around': 300,
 'though': 5424,
 'freemsg': 1996,
 'hey': 2382,
 'darl': 1259,
 'week': 5919,
 'word': 6054,
 'back': 412,
 'like': 3007,
 'fun': 2038,
 'still': 5093,
 'tb': 5308,
 'xxx': 6127,
 'chg': 915,
 'send': 4664,
 'rcv': 4324,
 'even': 1708,
 'brother': 705,
 'speak': 4978,
 'treat': 5573,
 'ai

In [31]:
# Unigrams + Bigrams

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(ngram_range=(1, 2))
X = cv.fit_transform(corpus)


In [33]:
cv.vocabulary_ #we can now see two words like "great world"

{'go': 11426,
 'jurong': 15334,
 'point': 23159,
 'crazi': 6088,
 'avail': 1821,
 'bugi': 3552,
 'great': 12270,
 'world': 34471,
 'la': 15898,
 'buffet': 3547,
 'cine': 4884,
 'got': 11998,
 'amor': 941,
 'wat': 33208,
 'go jurong': 11532,
 'jurong point': 15335,
 'point crazi': 23162,
 'crazi avail': 6090,
 'avail bugi': 1823,
 'bugi great': 3554,
 'great world': 12335,
 'world la': 34484,
 'la buffet': 15899,
 'buffet cine': 3548,
 'cine got': 4890,
 'got amor': 12001,
 'amor wat': 942,
 'ok': 21236,
 'lar': 15997,
 'joke': 15213,
 'wif': 33924,
 'oni': 21599,
 'ok lar': 21295,
 'lar joke': 16007,
 'joke wif': 15223,
 'wif oni': 33939,
 'free': 10210,
 'entri': 8613,
 'wkli': 34216,
 'comp': 5542,
 'win': 33993,
 'fa': 9156,
 'cup': 6257,
 'final': 9614,
 'tkt': 30773,
 'st': 28088,
 'may': 18259,
 'text': 29712,
 'receiv': 24458,
 'question': 23986,
 'std': 28281,
 'txt': 31674,
 'rate': 24176,
 'appli': 1306,
 'free entri': 10238,
 'entri wkli': 8622,
 'wkli comp': 34217,
 'comp w

In [ ]:
# Unigrams + Bigrams + Trigrams

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(ngram_range=(1, 3))
X = cv.fit_transform(corpus)


In [36]:
cv.vocabulary_

{'go': 20587,
 'jurong': 27962,
 'point': 42548,
 'crazi': 10894,
 'avail': 3183,
 'bugi': 6205,
 'great': 22382,
 'world': 63113,
 'la': 28984,
 'buffet': 6197,
 'cine': 8658,
 'got': 21852,
 'amor': 1650,
 'wat': 60764,
 'go jurong': 20845,
 'jurong point': 27963,
 'point crazi': 42553,
 'crazi avail': 10897,
 'avail bugi': 3186,
 'bugi great': 6208,
 'great world': 22521,
 'world la': 63136,
 'la buffet': 28985,
 'buffet cine': 6198,
 'cine got': 8669,
 'got amor': 21857,
 'amor wat': 1651,
 'go jurong point': 20846,
 'jurong point crazi': 27964,
 'point crazi avail': 42554,
 'crazi avail bugi': 10898,
 'avail bugi great': 3187,
 'bugi great world': 6209,
 'great world la': 22522,
 'world la buffet': 63137,
 'la buffet cine': 28986,
 'buffet cine got': 6199,
 'cine got amor': 8670,
 'got amor wat': 21858,
 'ok': 39004,
 'lar': 29156,
 'joke': 27751,
 'wif': 62094,
 'oni': 39757,
 'ok lar': 39128,
 'lar joke': 29177,
 'joke wif': 27770,
 'wif oni': 62125,
 'ok lar joke': 39131,
 'lar